name: Publish
on:
  push:
    branches:
      - main
jobs:
  release:
    if: github.event.pull_request.merged != true
    name: Build and publish seeds-packets
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
        with:
          # This makes Actions fetch all Git history so that Changesets can generate changelogs with the correct commits
          fetch-depth: 0
      - name: Setup Node.js 16.x
        uses: actions/setup-node@v3
        with:
          node-version: 16.14.2
          registry-url: 'https://registry.npmjs.org'
      - name: Configure git user
        run: git config --global user.email "techops+sproutjenkins@sproutsocial.com" && git config --global user.name "Sprout Jenkins"
      - name: Setup .npmrc
        run: |
          echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_PUBLISH_TOKEN }}" > .npmrc
      - name: Check if able to publish changes
        run: npm adduser && npm whoami
      - name: Install Dependencies
        run: yarn
      - name: Build
        run: yarn build
      - name: Publish
        run: npx lerna publish from-package --no-push --yes --no-verify-access
