name: Release
on:
  push:
    branches:
      - main
      - open_infrastructure
jobs:
  release:
    name: Build and release seeds-packets
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
        with:
          # This makes Actions fetch all Git history so that Changesets can generate changelogs with the correct commits
          fetch-depth: 0
      - name: Setup Node.js 16.x
        uses: actions/setup-node@v3
        with:
          node-version: 16.14.2
      - name: Install Dependencies
        run: yarn
      - name: Build
        run: yarn build
