name: Sync icons from Figma
on:
  schedule:
    # twice a day at 10:30am and 4:30pm
    - cron: '30 10,16 * * *'
  workflow_dispatch:
jobs:
  all:
    if: github.repository_owner == 'sproutsocial'
    name: Sync icons
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: 'main'
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      # Persist the yarn cache between builds, unless yarn.lock changes
      - name: Get yarn cache
        id: yarn-cache
        run: echo "::set-output name=dir::$(yarn cache dir)"
      - uses: actions/cache@v3
        with:
          path: ${{ steps.yarn-cache.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - name: Install Dependencies
        run: yarn install
      - name: Run Figma Sync
        env:
          FIGMA_TOKEN: ${{ secrets.FIGMA_TOKEN }}
          FIGMA_FILE_URL: ${{ secrets.FIGMA_FILE_URL }}
        run: yarn run figma-sync
      # Move the output files to our icons folder and run the icon linter on them
      # TODO: Do we need to run the linter? 
      # - run: |
      #     cp -R ./figma/svg/. ./icons/
      #     sudo rm -r ./figma
      #     yarn run icon-lint write "./icons/*.svg"
        # not actual JFROG creds obviously
        # just passing in to allow `yarn` command to run
        # (which seems to try to read in the .npmrc)
      # Create a PR if there are any file diffs
      - uses: peter-evans/create-pull-request@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "Chore: Sync icons from Figma"
          title: "Sync icons from Figma"
          branch: "figma-icon-sync"
          base: "main"
          body: |
            🚨 **This pull request has been created automatically** 🚨

            Racine uses a GitHub action to sync the svg files for our icons from our [master icon kit in Figma](https://www.figma.com/file/rc2gk7oZcvueGix29jvoCZ/Nectar-Icons). This script runs every day at 10:30am and 4:30pm.

            Whenever you need to release any icon changes into seeds-icons, you can merge this PR into `main` and include it in the next scheduled release of the package.

            **Be sure to take a look at the changes files to make sure everything is in order before merging.**
