name: Version
on:
  pull_request:
    types: [closed]
    branches:
      - main
      - open_infrastructure
  push:
    branches:
      - open_infrastructure
jobs:
  release:
    if: github.event.pull_request.merged == true
    name: Build and update seeds-packets versions
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
        with:
          # This makes Actions fetch all Git history so that Changesets can generate changelogs with the correct commits
          fetch-depth: 0
      - name: Setup Node.js 16.x
        uses: actions/setup-node@v3
        with:
          node-version: 16.14.2
      - name: Install Dependencies
        run: yarn
      - name: Build
        run: yarn build
      - name: Version
        run: npx lerna version --conventional-commits --yes --no-push
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
